CREATE TABLE IF NOT EXISTS namespaces (
  id UUID PRIMARY KEY,
  ip TEXT,
  size INTEGER DEFAULT 0,
  ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ip ON namespaces (ip);

CREATE INDEX IF NOT EXISTS idx_ts ON namespaces (ts DESC);
