/* eslint-disable */
// Generated by Wrangler by running `wrangler types --strict-vars=false --include-runtime false` (hash: 88c3fee1951ec1902bc794186bdab2dc)
declare namespace Cloudflare {
  interface Env {
    cloudkvData: KVNamespace
    GITHUB_SHA: string
    NAMESPACE_SIZE_LIMIT: number
    LOGFIRE_TOKEN: string
    LOGFIRE_ENVIRONMENT: string
    DB: D1Database
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string
}
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<Cloudflare.Env, 'GITHUB_SHA' | 'NAMESPACE_SIZE_LIMIT' | 'LOGFIRE_TOKEN' | 'LOGFIRE_ENVIRONMENT'>
    > {}
}
